### PR TITLE
Switch to docker multiplatform images and update packages

### PR DESCRIPTION
**Pull request by lucaslorentz**
Fix https://github.com/lucaslorentz/caddy-docker-proxy/issues/218

### CODE REVIEW

**Comment by francislavoie** [comment]
Maybe you could consider switching to the `caddy:<version>-builder` image variant now? https://hub.docker.com/_/caddy

**Comment by 0uep** [comment]
Hi @francislavoie 

I was not aware about `caddy:<version>-builder`. For your information, this is the way I build my docker image including three plugins:

```Dockerfile
FROM golang

RUN set -eux \
    ; \
    mkdir -p \
        /config/caddy \
        /data/caddy \
        /etc/caddy \
        /etc/gatekeeper/auth/local \
        /usr/share/caddy \
    ; \
    GO111MODULE=on go get -u github.com/caddyserver/xcaddy/cmd/xcaddy \
    ; \
    xcaddy build --with github.com/greenpau/caddy-auth-portal \
                 --with github.com/greenpau/caddy-auth-jwt \
                 --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 \
                 --output /usr/bin/caddy

# set up nsswitch.conf for Go's "netgo" implementation
# - https://github.com/docker-library/golang/blob/1eb096131592bcbc90aa3b97471811c798a93573/1.14/alpine3.12/Dockerfile#L9
RUN [ -e /etc/nsswitch.conf ] || echo 'hosts: files dns' > /etc/nsswitch.conf

# https://caddyserver.com/docs/conventions#file-locations
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME   /data

VOLUME /config
VOLUME /data
VOLUME /etc/caddy
VOLUME /etc/gatekeeper/auth

# Let's Encrypt TLS challenge
EXPOSE 80

# Official static web site
EXPOSE 443

# /metrics endpoint for Prometheus
EXPOSE 2019

WORKDIR /srv

ENV TZ "UTC0"
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
```

**Comment by lucaslorentz** [comment]
CDP is executed using a different CLI command.

Your last line should be something like:
```
CMD ["caddy", "docker-proxy"]
```

**Comment by 0uep** [comment]
Thank you very much @lucaslorentz 
I will check that when I will be motivated to migrate Caddyfile -> docker label

**Comment by lucaslorentz** [comment]
@francislavoie Tried to use caddy builder image, but it would increase too much the build time because each platform would need to download all golang modules.
I will stick with building all binaries directly in the build agent for now.

**Pull request merged**
