### PR TITLE
[RFC] virtual.port and virtual.host work, including virtual.port_1 -> caddy.route_1

### PR DESCRIPTION
**Pull request by SvenDowideit**
I thought I'd better play with https://github.com/lucaslorentz/caddy-docker-proxy/issues/181#issuecomment-674622078 so I hacked up a bad version without any attempt to templatize or make it configurable.

it takes the caddy specific labels

```
  whoami2:
    image: jwilder/whoami
    networks:
      - cirri_proxy
    labels:
      caddy: "*.${STACKDOMAIN:-loc.alho.st} ${STACKDOMAIN:-loc.alho.st}"
      caddy.route.reverse_proxy: "{{upstreams 8000}}"
      caddy.@whoami2.host: "short.${STACKDOMAIN:-loc.alho.st}"
      caddy.route: "@whoami2"
```

and converts it into a user/container centric "fact" label

```
  whoami2:
    image: jwilder/whoami
    networks:
      - cirri_proxy
    labels:
      virtual.port: 8000
      virtual.host: "short.${STACKDOMAIN:-loc.alho.st}"
```

without making it difficult to drop to the more expressive caddyfile syntax.

for example, mixing the 2 label types is possible (`caddy.route_1.import`)

```
  # Proxy with matches and 2 routes
  echo_0:
    image: brndnmtthws/nginx-echo-headers
    networks:
      - cirri_proxy
    labels:
      # 2 different host paths to the same container backend
      virtual.port: 8080
      virtual.host: "short.${STACKDOMAIN:-loc.alho.st}"

      # the second also requireing basic auth
      #caddy: "*.${STACKDOMAIN:-loc.alho.st} ${STACKDOMAIN:-loc.alho.st}"
      #caddy.@echo.host: "echo.${STACKDOMAIN:-loc.alho.st}"
      #caddy.route_1: "@echo"
      virtual.host_1: "echo.${STACKDOMAIN:-loc.alho.st}"
      caddy.route_1.import: users
      #caddy.route_1.reverse_proxy: "{{upstreams 8080}}"
      virtual.port_1: 8080
```

Obviously this implementation isn't useful for more than testing the idea - @lucaslorentz what do you think? is a less hacky version something you'd be interested in? and do you think it should begin as user defined macro's with arguments, or would it already be useful to mirror https://github.com/wemake-services/caddy-gen/ ?

### CODE REVIEW

**Comment by SvenDowideit** [comment]
And no, I'm not suggesting that you accept / merge the Dockerfile/Makefile changes, I just wanted things as familiar as possible so i could poke this out before i go to bed :)

**Comment by SvenDowideit** [comment]
tangentially related to https://github.com/caddyserver/caddy/issues/3200 - the replacements I want would be easier, but i'm sure there are other places where the nesting becomes complicated

**Comment by SvenDowideit** [comment]
So I've had some issues with caddyfile {env.}, so 

```
*.{env.STACKDOMAIN} {env.STACKDOMAIN} {
   reverse_proxy ... 
}
```

half works, and half doesn't (iirc, the route works, but the ssl cert fails - I'll report an issue in the caddyserver repo when I reproduce it again)

and so I may need to temporarily re-write this using labels like `virtual.ona.im.port` and `virtual.loc.alho.st.port` - so that the right wildcard matching happens

@lucaslorentz do you think its "ok" to define the 3 labels that I want to create for each macro as a line in a tmpl file? 
should I go for one tmpl file per macro, or am I heading off into weeds that aren't interesting to you?

**Comment by francislavoie** [comment]
There's two env syntaxes, you need to use the other one: https://caddyserver.com/docs/caddyfile/concepts#environment-variables

**Comment by SvenDowideit** [comment]
can't really use the other syntax - it gets evaluated too early (iirc)

**Comment by francislavoie** [comment]
Well `{env.}` is evaluated too late. It happens at runtime.

`{$}` happens when the Caddyfile is adapted to JSON. I'm not sure when you expect it to be evaluated exactly. What's your expectation?

**Comment by SvenDowideit** [comment]
mmm, I expected "runtime" to be when the json is used - ie, if there's `{env.SOMETHING}` in any key/value that is being read - like when the tls code rune, that it would be expanded then - 

basically, i don't grok how `{env.}` can ever be "too late" (I basically think of the cert getting code as runtime - I get the feeling that you're suggesting that happens beforehand?

**Comment by francislavoie** [comment]
Basically, for `{env.}` to work, the code that handles the config values needs to use the replacer, and that's not possible in every context at runtime for various reasons. Caddy doesn't do a pass through the entire JSON to replace `{env.}` placeholders, it leaves it until runtime when the server is actually provisioned and running to replace those, but it only works in certain places.

It's noted here: https://caddyserver.com/docs/conventions#placeholders

> Not all config fields support placeholders, but most do where you would expect it.

You just specifically ran into one where it's not supported

**Comment by SvenDowideit** [comment]
yeah - that note didn't read to me to mean what you've explained - and its really hard for the user to know where and when the exceptions happen without either more info, or maybe some linting.

**Comment by mholt** [comment]
We can probably use replacers in more places, it really just depends on when the individual config properties are used. If during http requests, then a lot of placeholders can be used. Most other places, only basic system wide placeholders such as env variables can be supported. (It just depends what context they are used in. Some parts of the code add placeholders based on what is happening. But all replacers support the basic things like env vars.)

**Comment by SvenDowideit** [comment]
I think I've explored the "expand labels by adding more labels" approach enough, and now that I've started to try out how @lucaslorentz 's proposal https://github.com/lucaslorentz/caddy-docker-proxy/issues/181#issuecomment-674557993 works, I agree, its better able to give my users the results we want.

so closing this as a good learning experiment.

**Pull request closed without merging**
