### PR TITLE
Fix regressions with multiple addresses being merged

### PR DESCRIPTION
**Pull request by lucaslorentz**
This PR fixes issues 2 and 3 reported on:
https://github.com/lucaslorentz/caddy-docker-proxy/issues/68

And second issue reported on:
https://github.com/lucaslorentz/caddy-docker-proxy/issues/67

Proxy directives still are generated whenever a `caddy.address` label is defined. This is an impact of making `caddy.targetport` optional. Any ideas on how to make port optional without causing this issue?

@jtyr @mrdrup

### CODE REVIEW

**Comment by lucaslorentz** [comment]
@jtyr @mrdrup
Please, use this image to test:
lucaslorentz/caddy-docker-proxy:test

**Comment by jtyr** [comment]
This PR fixed the issue for me.

**Comment by mrdrup** [comment]
Fixed issues 2 and 3 from #68 for me.

**Comment by jtyr** [comment]
@mrdrup Your issue 1 is fixed by this syntax:

```yaml
    labels:
      caddy: http://example.lan
      caddy.redir: https://example.lan{uri}
```

**Comment by mrdrup** [comment]
Yes, that works for me.

**Pull request merged**
